name: Release
on:
  push:
    tags:
    - 'v*'

env:
  IMAGE_NAME: "equinix/cloud-provider-equinix-metal"

jobs:
  images: # create images in docker hub
    name: Images
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up QEMU for cross-building
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Echo tag name
      run: echo running on tag ${GITHUB_REF#refs\/tags/}
    - name: tagname
      run: echo ::set-output name=tag::${GITHUB_REF#refs\/tags/}
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        tags: ${{ format('{0}:{1}', env.IMAGE_NAME, steps.tagname.outputs.tag) }} ${{ format('{0}:{1}', env.IMAGE_NAME, 'latest') }}

  release: # create a github actions release with necessary artifacts
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Echo tag name
      run: echo running on tag ${GITHUB_REF#refs\/tags/}
    - name: tagname
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: release template
      run: cat deploy/template/deployment.yaml | sed 's/RELEASE_TAG/'${{ steps.tagname.outputs.tag }}'/g' > /tmp/deployment.yaml
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Deployment Yaml Release Asset
      id: upload-release-asset-deployment
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: /tmp/deployment.yaml
        asset_name: deployment.yaml
        asset_content_type: application/yaml

