name: call test approver
on:
    push:
      branches:
        - "master"
        - "main"
    pull_request_review:
      types: [submitted]
  
jobs:
    get-run-id:
        runs-on: ubuntu-latest
        outputs:
          result: ${{ steps.get-run-id.outputs.result }}
        steps:
          - name: Get run ID for the artifact upload
            id: get-run-id
            uses: actions/github-script@v7
            with:
              script: |
                const { data } = await github.rest.actions.listWorkflowRuns({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    workflow_id: 'test-launcher.yaml',
                    head_sha: context.payload.pull_request.head.sha,
                    status: 'success'
                });
                if (data == null || data.workflow_runs.length == 0) {
                    throw new Error('No successful runs found');
                }
                const runId = data.workflow_runs[0].id; // Assuming the first one is the latest successful run
                return runId;
              result-encoding: string
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Report Run ID # useful for debugging
            run: echo "Run ID is ${{ steps.get-run-id.outputs.result }}"
    