name: call workflows to list workflow runs
on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner name'
        required: true
        default: ""
      repo:
        description: 'Repo name'
        required: true
        default: ""
      workflow_id:
        description: 'Workflow ID'
        required: true
        default: 'build.yml'
      sha:
        description: 'Head sha'
        required: true
        default: ""
      status:
        description: 'Status name'
        required: true
        default: 'success'

jobs:
  find:
    runs-on: ubuntu-latest
    steps:
    - name: Get run ID for the artifact upload
      id: get-run-id
      uses: actions/github-script@v7
      with:
        script: |
            const { data } = await github.rest.actions.listWorkflowRuns({
                owner: context.payload.inputs.owner,
                repo: context.payload.inputs.repo,
                workflow_id: context.payload.inputs.workflow_id,
                head_sha: context.payload.inputs.sha,
                status: context.payload.inputs.status
            });
            console.log(data);
            const runId = data.workflow_runs[0].id; // Assuming the first one is the latest successful run
            return runId;
        result-encoding: string
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print the run ID
      run: echo "The run ID is ${{ steps.get-run-id.outputs.result }}"
